### ISSUE TITLE
VM Abort on HDest Main

### ISSUE THREAD

**Issue by VBawss** [cyberc001/deusdoom#4]
VM execution aborted: Tried to read from address zero. In function parameter "type"
Called from DD_Aug_Cloak.toggle at cloak.zs line 151
Called from DD_Augmentation.Tick at augs.zs line 93
Called from DD_Aug_Cloak.Tick at cloak.zs line 70
Called from Actor.Spawn [Native]

This happens consistently with the latest build of HDest main every time you try to activate the cloak aug regardless of energy level or aug level.

**Comment by VBawss** [comment]
This also happens with the Radar Transparency aug as well.

**Comment by cyberc001** [comment]
Have you tried to update HDest compatibility patch? I did not write about it anywhere unfortunately.

**Comment by VBawss** [comment]
I just updated the patch and now it works flawlessly. Thank you!
